
version: 2.1

jobs:
  create_and_deploy_front_end:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: deploy new bucket
          command: |
            aws cloudformation deploy \
            --template-file bucket.yml \
            --stack-name "${CIRCLE_WORKFLOW_ID:0:7}" \ # ${CIRCLE_WORKFLOW_ID:0:7} takes the first 7 chars of the variable CIRCLE_CI_WORKFLOW_ID
            --parameter-overrides PipelineID="${CIRCLE_WORKFLOW_ID:0:7}"
      - run: aws s3 sync . s3://"${CIRCLE_WORKFLOW_ID}" --delete

    get_last_deployment_id:
      docker:
        - image: amazon/aws-cli
      steps:
        - name: query and save the id to a file that we can persist to the workspace
        - checkout
        - run:
          command: |
            aws cloudformation \
            list-exports --query "Exports[?Name==\`PipelineID\`].Value" \
            --no-paginate --output text > pipeline_id_output.txt
        - persist_to_workspace:
            root: ~/
            paths:
              - output.txt
    promote_to_production:
      docker:
        - image: amazon/aws-cli
      steps:
        - name: execute cloudfront.yml
        - checkout
        - run:
            command: |
              aws cloudformation deploy \
              --template-file cloudfront.yml \
              --stack-name production-distro \
              --parameter-overrides PipelineID="${CIRCLE_WORKFLOW_ID}"
    clean_up_old_front_end:
      docker:
        - image: amazon/aws-cli
      steps:
        - name: destroy the previous production version's S3 bucket and CloudFormation stack
        - attach_workspace:
            at: ~/
        - checkout
        - run:
            command: |
              OldPipelineID=`more pipeline_id_output.txt`
              aws s3 rm "s3://${OldPipelineID}" --recursive
              aws cloudformation delete-stack --stack-name "${CIRCLE_WORKFLOW_ID:0:7}"
workflows:
  my-workflow:
    jobs:
      - create_and_deploy_front_end
      - get_last_deployment_id:
          requires:
            - create_and_deploy_front_end
      - promote_to_production:
          requires:
            - get_last_deployment_id
      - clean_up_old_front_end:
          requires:
            - promote_to_production