
version: 2.1

jobs:
  create_and_deploy_front_end:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Deploy new bucket
          command: |
            aws cloudformation deploy \
            --template-file bucket.yml \
            --stack-name "${CIRCLE_WORKFLOW_ID:0:6}" \
            --parameter-overrides NAME="${CIRCLE_WORKFLOW_ID:0:6}"
      - run: aws s3 sync . s3://"${CIRCLE_WORKFLOW_ID:0:6}" --delete

  get_last_deployment_id:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run: yum install -y tar
      - run: yum install -y gzip
      - run:
          name: Query and save the id to a file that we can persist to the workspace
          command: |
            aws cloudformation \
            list-exports --query "Exports[?Name==\`PipelineID\`].Value" \
            --no-paginate --output text > ~/pipeline_id_output.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - pipeline_id_output.txt
  promote_to_production:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Execute cloudfront.yml 
          command: |
            aws cloudformation deploy \
            --template-file cloudfront.yml \
            --stack-name production-distro \
            --parameter-overrides PipelineID="${CIRCLE_WORKFLOW_ID}"
  clean_up_old_front_end:
    docker:
      - image: amazon/aws-cli
    steps:
      - run: yum install -y tar
      - run: yum install -y gzip
      - attach_workspace:
          at: ~/
      - checkout
      - run:
          name: destroy the previous production version's S3 bucket and CloudFormation stack
          command: |
            OldPipelineID=`more ~/pipeline_id_output.txt`
            aws s3 rm "s3://${OldPipelineID}" --recursive
            aws cloudformation delete-stack --stack-name "${CIRCLE_WORKFLOW_ID:0:6}"
workflows:
  my-workflow:
    jobs:
      - create_and_deploy_front_end
      - get_last_deployment_id:
          requires:
            - create_and_deploy_front_end
      - promote_to_production:
          requires:
            - get_last_deployment_id
      - clean_up_old_front_end:
          requires:
            - promote_to_production